apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    name: nginx-service
    environment: DEV
spec:
  type: NodePort
  selector:
  # you should provide pod labels here
    name: saivinay
    dept: cse
    year: twenty
  ports:
  - name: http-port
    protocol: TCP
    # service port
    port: 80
    # pod port
    targetPort: 80

---

kind: Pod
apiVersion: v1
metadata:
  name: labelpod
  namespace: roboshop
  labels:
    name: saivinay
    dept: cse
    year: twenty
spec:
  containers:
  - name: nginx
    image: nginx






    
   
