apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  selector:
    dept: cse
  ports:
  - name: http
    protocol: tcp
    port: 80
    target: 80

---
kind: Pod
apiVersion: v1
metadata:
  name: debug-pod
  labels:
    name: saivinay
    dept: cse
    year: twenty
spec:
  containers:
  - name: almalinux
    image: "almalinux:8"
    command: ["sleep" , "20000"]


