kind: Pod
apiVersion: v1
metadata:
  name: label
  labels:
    name: k8
    language: yamallanguage
    course: 6weeks
  annotations:
    kakisai.vgmail.com: myusergamil
spec:
  containers:
  - image: nginx
    name: label
    ports:
    - containerPort: 80
    resources :
      requests: 
        cpu: "0.2"
        memory: "128mi"
      limits: 
        cpu: "0.3"
        memory: "150mi"










#creating resource as pod and name of the pord as nginx ========image as nginx ====== and image name was nginx 
# docker run -p 80:80 nginx ==> pull image from docker hub and create container